<section class="banner" id="home">
    <div class="cabecalho-home">
        <header> <!--inicio header-->
                <nav class="navbar navbar-expand-md navbar-light navbar-transparente"> <!--inicio nav-->
                    <div class="container"> <!--inicio container-->
                        
                        <a href="#"><img class="logo" src="img/logo/logoPngSf.png"></a>

                        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal" >  <!--inicio button-->
                        <i class="fas fa-bars text-white"></i>
                        </button> <!--final button-->

                        <div class="collapse navbar-collapse" id="nav-principal"> <!-- inicio div collapse-->

                        <ul class="navbar-nav ml-auto"> <!--inicio ul-->
                            <li class="nav-item">
                            <a href="#" class="nav-link" id="abrir">Login</a>
                            </li>
                            <li class="nav-item">
                            <a href="/cadastro" class="nav-link">Cadastro</a>
                            </li>
                            <li class="nav-item">
                            <a href="/perguntasFrequentes" class="nav-link">Perguntas Frequentes</a>
                            </li>
                        </ul> <!--final ul-->

                        </div> <!--final div collapse-->

                    </div> <!--final container-->

                </nav> <!--final nav-->

        </header> <!--final header-->

        <div id="modal" class="hide"> <!-- Inicio modal=Preenchimento da tela toda// Hide=Esconder e só apararecer quando clicar em login -->
            <div class="content"> <!--Inicio content(todo o conteudo dentro do modal) -->
                <div class="header"> 
                    <h1>Login</h1>
                    <a href="#" id="fechar">Fechar</a>
                </div>

                <form action="">
                    <label for="search">Email</label>
                    <div class="search field">
                        <input type="text" name="search"  placeholder="email@exemplo.com">
                        <div class="chk" >

                        </div>
                    </div>

                    <label for="search">Senha</label>
                    <div class="search field">
                        <input type="text" name="senha" id="senha" class="senha" placeholder="Sua senha">
                        <label class="chk">
                            <img class="olho" id="imgOlho" src="img/senha/olhoFechado.svg" alt="" onclick="mostrarSenha()">
                        </label> 
                    </div>
                </form>
            </div>
        </div>
    
                
        <section class="container listaDePresentes">
            <div class="txt">
                <h1>Lista de presentes</h1>
                <p>O jeito mais fácil de presentear e ser presenteado em <br> 
                    todos os momentos importantes de sua vida</p>                            
            </div>
                    
            <div class="botaoRolagem">
                <a href="#part1"><img class="svg-setas" src="img/setas/svg/seta-para-baixo.svg" onload="SVGInject(this)"></a>
                <div class="back-to-top" href="#"></div>
            </div>
        </section>
    </div>           
</section>

<section class="container divOpcoes">
        <div id="part1" class="opcoes">

            <div class="escolher">
                <h1><img class="svg-icones" src="img/presentes/presente.svg" onload="SVGInject(this)"> Listas de presentes</h1>
                <p>Aqui você cria listas para ser presenteado <br>
                em todos os momentos de sua vida</p>
                <h2><a href="/cadastro">CRIAR MINHA LISTA</a></h2>
            </div>
            
            <div class="presentear">
                <h1><img class="svg-icones" src="img/coracao/terra.svg" onload="SVGInject(this)"> Presenteie agora</h1>
                <p>Está procurando uma lista?<br>
                Aqui você encontra a lista dos seus amigos e escolhe o presente perfeito!</p>
                <h2><a href="/cadastro">PROCURAR UMA LISTA</a></h2>
            </div>

        </div>

        <div class="botaoRolagem">
            <a href="#home"><img class="svg-setas" src="img/setas/svg/seta-para-cima.svg" onload="SVGInject(this)"></a>
        </div>
</section>


<footer>            
  <div class="container">
    <a href="/" class="titulo">Presentei.com</a> 
  </div>
</footer>

             
    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 