<section class="banner" id="home">
    <div class="cabecalho-home">
    <header> <!--inicio header-->
                    <nav class="navbar navbar-expand-md navbar-light navbar-transparente"> <!--inicio nav-->
                        <div class="container"> <!--inicio container-->
                            <a href="/logado"><img class="logo" src="img/logo/logoPngSf.png"></a>


                            <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">  <!--inicio button-->
                            <i class="fas fa-bars text-white"></i>
                            </button> <!--final button-->

                            <div class="collapse navbar-collapse" id="nav-principal"> <!-- inicio div collapse-->

                            <ul class="navbar-nav ml-auto"> <!--inicio ul-->                            
                                <li class="nav-item">
                                <a href="/minhaConta" class="nav-link"><?= $this->view->nome?></a>
                                </li>
                                <li class="nav-item">
                                <a href="/escolherLista" class="nav-link">Minha lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/procurarListaLogado" class="nav-link">Procurar Lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/sair" class="nav-link">Sair</a>
                                </li>
                            </ul> <!--final ul-->

                            </div> <!--final div collapse-->

                        </div> <!--final container-->

                    </nav> <!--final nav-->

            </header> <!--final header-->

    <section class="container lista">
            <section class="listaDePresente">            
                <div class="iconesPresente">

                    <div class="pngIconesPresente">
                         <img src="img/lista/fotografia-de-casamento.png" alt="">
                         <a href="/criarListaCasamento" type="submit" class="btn btn-custom btn-sm">Casamento</a>
                    </div>

                    <div class="pngIconesPresente">
                        <img src="img/lista/festa-de-aniversario.png" alt="">
                        <button type="submit" class="btn btn-custom btn-sm">Aniversario</button>
                    </div>

                    <div class="pngIconesPresente">
                        <img src="img/lista/carrinho-de-bebe.png" alt="">
                        <button type="submit" class="btn btn-custom btn-sm">Chá de bebê</button>
                    </div>

                    <div class="pngIconesPresente">
                        <img src="img/lista/utensilios-de-cozinha.png" alt="">
                        <button type="submit" class="btn btn-custom btn-sm">Chá de cozinha</button>
                    </div>



                        <!-- <a href="#carousel" class="carousel-control-prev" data-slide="prev">
                            <img class="png-setas" src="img/setas/png/seta-esquerda.png">                    
                        </a>

                        <a href="#carousel" class="carousel-control-next" data-slide="next">
                            <img class="png-setas" src="img/setas/png/seta-direita.png">                    
                        </a> -->
                    </div> 

                    <section class="propriaLista">
                        <p>Selecione uma das listas que criamos pra você ou então crie sua própria lista e selecione seus produtos</p>
                        <button type="submit" class="btn btn-custom btn-sm">Criar minha própria lista</button>
                    </section>    

                </div>


            </section>


    </section>


<footer>            
  <div class="container">
    <a href="/" class="titulo">Presentei.com</a> 
  </div>
</footer>

    
    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 