<section class="banner" id="home">
    <div class="cabecalho-home">
        <header> <!--inicio header-->
                    <nav class="navbar navbar-expand-md navbar-light navbar-transparente"> <!--inicio nav-->
                        <div class="container"> <!--inicio container-->
                            <a href="/logado"><img class="logo" src="img/logo/logoPngSf.png"></a>


                            <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">  <!--inicio button-->
                            <i class="fas fa-bars text-white"></i>
                            </button> <!--final button-->

                            <div class="collapse navbar-collapse" id="nav-principal"> <!-- inicio div collapse-->

                            <ul class="navbar-nav ml-auto"> <!--inicio ul-->                            
                                <li class="nav-item">
                                <a href="/minhaConta" class="nav-link"><?= $this->view->nome?></a>
                                </li>
                                <li class="nav-item">
                                <a href="/escolherLista" class="nav-link">Minha lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/procurarListaLogado" class="nav-link">Procurar Lista</a>
                                </li>
                                <li class="nav-item">
                                <a href="/sair" class="nav-link">Sair</a>
                                </li>
                            </ul> <!--final ul-->

                            </div> <!--final div collapse-->

                        </div> <!--final container-->

                    </nav> <!--final nav-->

            </header> <!--final header-->
    
                
        <section class="container listaDePresentes">
            <div class="txt">
                <h1>Lista de presentes</h1>
                <p>O jeito mais fácil de presentear e ser presenteado em <br> 
                    todos os momentos importantes de sua vida</p>                            
            </div>
                    
            <div class="botaoRolagem">
                <a href="#part1"><img class="svg-setas" src="img/setas/svg/063-down-arrow-7.svg" onload="SVGInject(this)"></a>
            </div>
        </section>
    </div>           
</section>

<section class="container divOpcoes">
        <div id="part1" class="opcoes">

            <div class="escolher">
                <h1><img class="svg-icones" src="img/presentes/presente.svg" onload="SVGInject(this)"> Listas de presentes</h1>
                <p>Aqui você cria listas para ser presenteado <br>
                Em todos os momentos de sua vida</p>
                <h2><a href="/escolherLista">CRIAR MINHA LISTA</a></h2>
            </div>
            
            <div class="presentear">
                <h1><img class="svg-icones" src="img/coracao/terra.svg" onload="SVGInject(this)"> Presenteie agora</h1>
                <p>Está procurando uma lista?<br>
                Aqui você encontra a lista de seus amigos e escolhe o presente</p>
                <h2><a href="/logado">PROCURAR UMA LISTA</a></h2>
            </div>

        </div>

        <div class="botaoRolagem">
            <a href="#home"><img class="svg-setas" src="img/setas/svg/005-up-arrow-7.svg" onload="SVGInject(this)"></a>
        </div>
</section>


<footer>            
  <div class="container">
    <a href="/" class="titulo">Presentei.com</a> 
  </div>
</footer>

    

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 